language: csharp
mono: none
dotnet: 2.1
script: 
  - dotnet build Blip.HttpClient.sln
  - dotnet test Blip.HttpClient.Tests/Blip.HttpClient.Tests.csproj
after_success:
    - ./tools/opencover/OpenCover.Console.exe -register:user -target:"/usr/share/dotnet/sdk/2.1.402/dotnet" -targetargs:test -output:".\MyProject_coverage.xml" -oldstyle
    - ./tools/codecov/codecov.exe -f "MyProject_coverage.xml" -t $CODECOV_TOKEN